package com.bunsen.studentmis.model;

public enum EAcademicUnit {
    PROGRAMME(null),
        UNDERGRADUATE(PROGRAMME),
            FACULTY_OF_THEOLOGY(UNDERGRADUATE),
                BACHELOR_OF_THEOLOGY(FACULTY_OF_THEOLOGY),
            FACULTY_OF_HEALTH_SCIENCE(UNDERGRADUATE),
                BACHELOR_OF_SCIENCE_IN_NURSING(FACULTY_OF_HEALTH_SCIENCE),
                BACHELOR_OF_SCIENCE_IN_MIDWIFERY(FACULTY_OF_HEALTH_SCIENCE),
            FACULTY_OF_INFORMATION_TECHNOLOGY_UN(UNDERGRADUATE),
                BACHELOR_IN_SOFTWARE_ENGINEERING(FACULTY_OF_INFORMATION_TECHNOLOGY_UN),
                BACHELOR_IN_INFORMATION_MANAGEMENT(FACULTY_OF_INFORMATION_TECHNOLOGY_UN),
                BACHELOR_IN_NETWORKS_AND_COMMUNICATION_SYSTEM(FACULTY_OF_INFORMATION_TECHNOLOGY_UN),
            FACULTY_OF_BUSINESS_UN(UNDERGRADUATE),
                ACCOUNTING_UN(FACULTY_OF_BUSINESS_UN),
                MANAGEMENT_UN(FACULTY_OF_BUSINESS_UN),
                FINANCE_UN(FACULTY_OF_BUSINESS_UN),
                MARKETING_UN(FACULTY_OF_BUSINESS_UN),

            FACULTY_OF_EDUCATION(UNDERGRADUATE),
                BACHELOR_OF_EDUCATION_IN_ACCOUNTING_AND_INFORMATION_TECHNOLOGY(FACULTY_OF_EDUCATION),
                BACHELOR_OF_EDUCATION_IN_ENGLISH_AND_FRENCH_LANGUAGE_LITERATURE(FACULTY_OF_EDUCATION),
                BACHELOR_OF_EDUCATION_IN_HISTORY_AND_GEOGRAPHY(FACULTY_OF_EDUCATION),
    MASTERS(PROGRAMME),
        FACULTY_OF_INFORMATION_TECHNOLOGY_MS(MASTERS),
            MASTERS_OF_SCIENCE_IN_BIG_DATA_ANALYTICS(FACULTY_OF_INFORMATION_TECHNOLOGY_MS),
        FACULTY_OF_BUSINESS_ADMINISTRATION(MASTERS),
            MASTERS_IN_ACCOUNTING(FACULTY_OF_BUSINESS_ADMINISTRATION),
            MASTERS_IN_MANAGEMENT(FACULTY_OF_BUSINESS_ADMINISTRATION),
            MASTERS_IN_FINANCE(FACULTY_OF_BUSINESS_ADMINISTRATION),
            MASTERS_IN_HUMAN_RESOURCE_MANAGEMENT(FACULTY_OF_BUSINESS_ADMINISTRATION),
            MASTERS_IN_PROJECT_MANAGEMENT(FACULTY_OF_BUSINESS_ADMINISTRATION);
    private EAcademicUnit parent=null;
    private EAcademicUnit(EAcademicUnit parent) {
        this.parent=parent;
    }
    public EAcademicUnit getParent() {
        return parent;
    }
}
